

export const REFETCH_CHATS = 'REFETCH_CHATS';
export const ALERT = 'ALERT';

export const NEW_ATTACHMENT = 'ALERT';
export const NEW_MESSAGE_ALERT = 'NEW_MESSAGE_ALERT';

export const NEW_REQUEST = 'NEW_REQUEST';

export const NEW_MESSAGE = 'NEW_MESSAGE';

export const START_OR_STOP_TYPING = 'START_OR_STOP_TYPING';


export const USER_CONNECTED = 'USER_CONNECTED';
export const UPDATE_USER_STATUS = 'UPDATE_USER_STATUS';
export const UPDATE_USER_LAST_SEEN = 'UPDATE_USER_LAST_SEEN';

export const UPDATE_USER_STATUS_FROM_FRONT = 'UPDATE_USER_STATUS_FROM_FRONT';

// export const LAST_MESSAGE_UPDATE = 'LAST_MESSAGE_UPDATE';
